---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts"
  set_fact:
    ansible_distribution: centos
    when: ansible_distribution == "RedHat"

- name: Subscribe to required channels
  import_role:
    name: spacewalk-client
    tasks_from: channel.yml
  vars:
    channels: '{{ ossec_rhn_channels }}'

  #- name: "RedHat | Install atomicorp repo"
  #yum:
  #  name: "https://www.atomicorp.com/channels/atomic/centos/{{ansible_distribution_major_version}}/x86_64/RPMS/atomic-release-{{ ossec_server_atomic_release }}.el{{ansible_distribution_major_version}}.art.noarch.rpm"
  #  state: present

  #- name: "RedHat | Install epel repo"
  #yum:
  #  name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm"
  #  state: present

- name: "RedHat | Remove ossec-hids-agent"
  yum:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - ossec-hids-agent
  tags:
    - init

- name: "RedHat | Install ossec-hids-server"
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - ossec-hids
    - ossec-hids-server
  tags:
    - init

- name: "Set Distribution CIS filename for RHEL5"
  set_fact:
    cis_distribution_filename: cis_rhel5_linux_rcl.txt
  when: ansible_distribution_major_version == "5"

- name: "Set Distribution CIS filename for RHEL6"
  set_fact:
    cis_distribution_filename: cis_rhel6_linux_rcl.txt
  when: ansible_distribution_major_version == "6"

- name: "Set Distribution CIS filename for RHEL7"
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when: ansible_distribution_major_version == "7"

- name: "Set ossec deploy facts for RedHat"
  set_fact:
    ossec_server_config_filename: ossec-server.conf
    ossec_init_name: ossec-hids

- name: Make sure services can pass through firewall
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ item[0] }} port port={{ item[1].port }} protocol={{ item[1].protocol }} accept"
    permanent: true
    immediate: true
    zone: public
    state: enabled
  with_nested:
    - '{{ ossec_firewall_permit }}'
    - [ { port: 1514, protocol: udp }, { port: 1515, protocol: tcp } ]
  when: firewalld_enabled and ossec_firewall_permit is defined
  notify: reload firewalld
  tags:
    - firewall
